./readBin.native test_cases/global.wasm
./readBin.native test_cases/callback.wasm
./readBin.native test_cases/example.wasm
./readBin.native test_cases/finalize.wasm
./readBin.native test_cases/hello.wasm
./readBin.native test_cases/hostref.wasm
./readBin.native test_cases/memory.wasm
./readBin.native test_cases/multi.wasm
./readBin.native test_cases/reflect.wasm
./readBin.native test_cases/serialize.wasm
./readBin.native test_cases/start.wasm
./readBin.native test_cases/table.wasm
./readBin.native test_cases/threads.wasm
./readBin.native test_cases/trap.wasm